# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Docker Images

on:
  push:
    branches:
      - ros2
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push gazebo garden image with ros humble
        uses: docker/build-push-action@v4
        with:
          context: dockerfiles/ignition/igition-humble/
          push: true
          tags: ${{ env.REGISTRY }}/remaro-network/ignition-humble:latest
          labels: latest

      - name: Build and push ignition-ardusub-humble image
        uses: docker/build-push-action@v4
        with:
          context: dockerfiles/ignition-ardusub/ignition-ardusub-humble/
          push: true
          build-args: BASE_IMAGE=${{ env.REGISTRY }}/remaro-network/ignition-humble:latest
          tags: ${{ env.REGISTRY }}/remaro-network/ignition-ardusub-humble:latest

      - name: Build and push ignition hackathon image
        uses: docker/build-push-action@v4
        with:
          context: dockerfiles/ignition-hackathon/ignition-hackathon-humble/
          push: true
          # tags: ${{ env.REGISTRY }}/remaro-network/hackathon:latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: BASE_IMAGE=${{ env.REGISTRY }}/remaro-network/ignition-ardusub-humble:latest
